export enum Position {
    STCL = 'STCL',
    STC = 'STC',
    STCR = 'STCR',
    AML = 'AML',
    AMCL = 'AMCL',
    AMC = 'AMC',
    AMCR = 'AMCR',
    AMR = 'AMR',
    ML = 'ML',
    MCL = 'MCL',
    MC = 'MC',
    MCR = 'MCR',
    MR = 'MR',
    WBL = 'WBL',
    DMCL = 'DMCL',
    DMC = 'DMC',
    DMCR = 'DMCR',
    WBR = 'WBR',
    DL = 'DL',
    DCL = 'DCL',
    DC = 'DC',
    DCR = 'DCR',
    DR = 'DR',
    GK = 'GK'
}